instance creation
new
	self error: 'Use #database:name:'